### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by solomon-ma** [TEA-Lab/diffusion_reward#2]
Error executing job with overrides: ['dataset=metaworld']
Traceback (most recent call last):
  File "scripts/train_vqgan.py", line 136, in <module>
    main()
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "scripts/train_vqgan.py", line 132, in main
    TrainVQGAN(cfg)
  File "scripts/train_vqgan.py", line 28, in __init__
    self.train(args)
  File "scripts/train_vqgan.py", line 54, in train
    train_dataset, val_dataset = load_data(args)
  File "/home/solomon/workspace/diffusion_reward/diffusion_reward/models/codec_models/vqgan/utils.py", line 51, in load_data
    train_loader = DataLoader(train_data, batch_size=args.batch_size, shuffle=True)
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/solomon/miniconda3/envs/diffusion_reward/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

Could you give me an idea to organize the dataset?

my data directory shows below:
![image](https://github.com/TEA-Lab/diffusion_reward/assets/16464813/3782cc30-954f-430b-b22f-3706c8d1ecd4)

**Comment by TaoHuang13** [comment]
Hi. Have you placed the data under `/video_dataset`, as said in README?

**Comment by solomon-ma** [comment]
Thanks for your reply
I placed the dataset in other directory ,and change the data path in config



---Original---
From: "Tao ***@***.***&gt;
Date: Sun, Mar 3, 2024 18:43 PM
To: ***@***.***&gt;;
Cc: "Ma ***@***.******@***.***&gt;;
Subject: Re: [TEA-Lab/diffusion_reward] ValueError: num_samples should be apositive integer value, but got num_samples=0 (Issue #2)




 
Hi. Have you placed the data under /video_dataset, as said in README?

**Comment by TaoHuang13** [comment]
Hi. Got it. You may take a look at [this line](https://github.com/TEA-Lab/diffusion_reward/blob/f6b5f838d1ab947fe300af9a3424788b3e645508/diffusion_reward/models/codec_models/vqgan/utils.py#L18) and modify it to fit your condition, as we hard code the loading path. Meanwhile, you also need to modify the loading path of VideoGPT, and VQDiffusion to ensure successful running.

That said, placing data under the suggested path would avoid these issues.
